---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    type: appserver
    author: charan
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: tomcat
          image: tomcat:10
...

