---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8080
      resources:
        requests:
          memory: 64Mi
          cpu: 200m
        limits:
          memory: 128Mi
          cpu: 500m
...
