---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    author: charan
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: db
    author: charan
...
